#Example workflow for deployment

name: Deploy

env:
  imageName: "example"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ imageName }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      #TODO DEPLOYMENT